let stockProductos = [
    {id: 1,
     nombre: "Cata de Vinos Inicial", 
     tipo: "curso", 
     cantidad: 1, 
     desc: "Orientado a las personas que quieran iniciarse en el mundo del vino, ya sea para aplicarlo en su ámbito profesional o como aficionados de manera práctica.", 
     precio: 1500, 
     img: './img/curso1.jpg'},
    {id: 2, 
    nombre: "Cata de Vinos Avanzado", 
    tipo: "curso", 
    cantidad: 1, 
    desc: "Orientado a las personas que hayan realizado el curso inicial de vinos y que quieran profundizar en los conocimientos sobre vinos y las técnicas de cata.", 
    precio: 2500, 
    img: './img/curso2.jpg'},
    {id: 3, 
    nombre: "Comercialización de Vinos", 
    tipo: "curso", 
    cantidad: 1, 
    desc: "Orientado a aquellas personas que se encuentren trabajando o que quieran ingresar a la industria vitivinícola. Misión y objetivos de la bodega. Diseño de producto.", 
    precio: 4500, 
    img: './img/curso4.jpg'},
]